name: Zola on GitHub Pages

on:
 push:
  branches:
   - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Create deploy directory
      run: mkdir deploy
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.18.0
      env:
        BUILD_DIR: deploy
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PAGES_BRANCH: deploy
